# Generated by Django 4.2.2 on 2023-06-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_status_task_signin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lead_time',
            field=models.DateTimeField(),
        ),
    ]
