# Generated by Django 4.2.2 on 2023-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_task_lead_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
